import React, { createContext, useContext, useState, useCallback, useEffect } from 'react';
import { AppState, AppStateStatus } from 'react-native';
import { StorageEventBus, STORAGE_KEYS } from '@/lib/storage-event-bus';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {
  sendSubscriptionApprovedNotification,
  sendSubscriptionRejectedNotification,
  sendSubscriptionActivatedNotification,
} from './subscription-notification-service';
import { sendNotification } from './send-notification';

const STORAGE_KEY_REQUESTS = STORAGE_KEYS.SUBSCRIPTION_REQUESTS;
const STORAGE_KEY_HISTORY = STORAGE_KEYS.SUBSCRIPTION_HISTORY;

export interface SubscriptionRequest {
  id: string;
  userId: string;
  userName: string;
  userPhone: string;
  userRole: 'residential' | 'commercial' | 'industrial' | 'collector' | 'recycler';
  subscriptionPlan: string;
  planId?: string;
  planPrice: number;
  affiliationFee?: number;
  requestDate: string;
  status: 'pending' | 'approved' | 'rejected' | 'activated';
  rejectionReason?: string;
  approvedBy?: string;
  approvalDate?: string;
  activationDate?: string;
  paymentMethod?: string;
  /** The payment reference generated by createPayment (e.g. LTC1A2B3C) */
  paymentReference?: string;
  /** The internal payment record ID from PaymentsContext */
  paymentId?: string;
  /** The transaction ID entered by the user (from their mobile money SMS) */
  transactionId?: string;
  /** Amount paid in ZMW */
  amountPaid?: number;
  notes?: string;
}

export interface ApprovalAction {
  id: string;
  requestId: string;
  adminId: string;
  adminName: string;
  adminRole: 'superadmin' | 'finance';
  action: 'approved' | 'rejected' | 'activated';
  reason?: string;
  timestamp: string;
  notes?: string;
}

/**
 * Callback used by activateAccount to persist the subscription to the user's
 * auth profile. Injected via SubscriptionApprovalProvider props so the context
 * does not need to import auth-context (avoids circular deps).
 */
export type ActivateSubscriptionCallback = (
  userId: string,
  subscription: {
    planId: string;
    planName: string;
    expiresAt: string;
    pickupsRemaining: number;
  },
) => Promise<void>;

interface SubscriptionApprovalContextType {
  pendingRequests: SubscriptionRequest[];
  approvalHistory: ApprovalAction[];
  isLoading: boolean;
  approveRequest: (requestId: string, adminId: string, adminName: string, adminRole: string, notes?: string) => void;
  rejectRequest: (requestId: string, adminId: string, adminName: string, reason: string, notes?: string) => void;
  activateAccount: (requestId: string, adminId: string, adminName: string) => void;
  getRequestById: (requestId: string) => SubscriptionRequest | undefined;
  getRequestsByStatus: (status: SubscriptionRequest['status']) => SubscriptionRequest[];
  /** Returns all requests for a specific userId, sorted newest first */
  getRequestsByUserId: (userId: string) => SubscriptionRequest[];
  getApprovalHistory: (requestId?: string) => ApprovalAction[];
  addSubscriptionRequest: (request: Omit<SubscriptionRequest, 'id' | 'status' | 'requestDate'>) => Promise<string>;
  getStats: () => { pending: number; approved: number; activated: number; rejected: number };
}

const SubscriptionApprovalContext = createContext<SubscriptionApprovalContextType | undefined>(undefined);

/** Seed data shown until real requests arrive */
const SEED_REQUESTS: SubscriptionRequest[] = [
  {
    id: 'req-seed-001',
    userId: 'user-001',
    userName: 'John Banda',
    userPhone: '+260960123456',
    userRole: 'residential',
    subscriptionPlan: 'Premium',
    planPrice: 180,
    requestDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'pending',
    paymentMethod: 'MTN Mobile Money',
    paymentReference: 'MTN-2024-001',
  },
  {
    id: 'req-seed-002',
    userId: 'user-002',
    userName: 'Sarah Mwale',
    userPhone: '+260961234567',
    userRole: 'commercial',
    subscriptionPlan: 'Business',
    planPrice: 500,
    requestDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'pending',
    paymentMethod: 'Airtel Money',
    paymentReference: 'AIR-2024-001',
  },
  {
    id: 'req-seed-003',
    userId: 'user-003',
    userName: 'Peter Chanda',
    userPhone: '+260962345678',
    userRole: 'collector',
    subscriptionPlan: 'Collector Basic',
    planPrice: 0,
    affiliationFee: 350,
    requestDate: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    status: 'pending',
    paymentMethod: 'MTN Mobile Money',
    paymentReference: 'MTN-2024-002',
  },
];

const SEED_HISTORY: ApprovalAction[] = [
  {
    id: 'action-seed-001',
    requestId: 'req-seed-004',
    adminId: 'admin-001',
    adminName: 'Admin User',
    adminRole: 'superadmin',
    action: 'approved',
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    notes: 'Payment verified and confirmed',
  },
];

interface SubscriptionApprovalProviderProps {
  children: React.ReactNode;
  /**
   * Optional callback to persist the activated subscription to the user's
   * auth profile. Pass `updateUser` from `useAuth()` here.
   * When provided, activateAccount will call this with the userId and
   * subscription data derived from the request.
   */
  onActivateSubscription?: ActivateSubscriptionCallback;
}

export function SubscriptionApprovalProvider({
  children,
  onActivateSubscription,
}: SubscriptionApprovalProviderProps) {
  const [pendingRequests, setPendingRequests] = useState<SubscriptionRequest[]>(SEED_REQUESTS);
  const [approvalHistory, setApprovalHistory] = useState<ApprovalAction[]>(SEED_HISTORY);
  const [isLoading, setIsLoading] = useState(true);

  // ── Hydrate from AsyncStorage on mount ──────────────────────────────────────
  const loadFromStorage = useCallback(async () => {
    try {
      const [storedRequests, storedHistory] = await Promise.all([
        AsyncStorage.getItem(STORAGE_KEY_REQUESTS),
        AsyncStorage.getItem(STORAGE_KEY_HISTORY),
      ]);

      if (storedRequests) {
        const parsed: SubscriptionRequest[] = JSON.parse(storedRequests);
        const realEntries = parsed.filter(r => !r.id.startsWith('req-seed-'));
        const seedIds = new Set(SEED_REQUESTS.map(s => s.id));
        const storedSeedEntries = parsed.filter(r => seedIds.has(r.id));
        const mergedSeeds = SEED_REQUESTS.map(seed =>
          storedSeedEntries.find(s => s.id === seed.id) ?? seed
        );
        setPendingRequests([...realEntries, ...mergedSeeds]);
      }

      if (storedHistory) {
        const parsed: ApprovalAction[] = JSON.parse(storedHistory);
        const seedHistoryIds = new Set(SEED_HISTORY.map(h => h.id));
        const realHistory = parsed.filter(h => !seedHistoryIds.has(h.id));
        setApprovalHistory([...realHistory, ...SEED_HISTORY]);
      }
    } catch (err) {
      console.warn('[SubscriptionApproval] Failed to load from storage:', err);
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    loadFromStorage();
  }, [loadFromStorage]);

  // Real-time: reload when another context writes to these keys
  useEffect(() => {
    const unsubReq = StorageEventBus.subscribe(STORAGE_KEY_REQUESTS, loadFromStorage);
    const unsubHist = StorageEventBus.subscribe(STORAGE_KEY_HISTORY, loadFromStorage);
    return () => { unsubReq(); unsubHist(); };
  }, [loadFromStorage]);

  // Cross-device: reload when app returns to foreground
  useEffect(() => {
    let appStateRef: AppStateStatus = AppState.currentState;
    const sub = AppState.addEventListener('change', (next) => {
      if (appStateRef.match(/inactive|background/) && next === 'active') {
        loadFromStorage();
      }
      appStateRef = next;
    });
    return () => sub.remove();
  }, [loadFromStorage]);

  // ── Persist helpers ──────────────────────────────────────────────────────────
  const saveRequests = useCallback(async (requests: SubscriptionRequest[]) => {
    try {
      await AsyncStorage.setItem(STORAGE_KEY_REQUESTS, JSON.stringify(requests));
      StorageEventBus.emit(STORAGE_KEY_REQUESTS);
    } catch (err) {
      console.warn('[SubscriptionApproval] Failed to save requests:', err);
    }
  }, []);

  const saveHistory = useCallback(async (history: ApprovalAction[]) => {
    try {
      await AsyncStorage.setItem(STORAGE_KEY_HISTORY, JSON.stringify(history));
      StorageEventBus.emit(STORAGE_KEY_HISTORY);
    } catch (err) {
      console.warn('[SubscriptionApproval] Failed to save history:', err);
    }
  }, []);

  // ── Actions ──────────────────────────────────────────────────────────────────

  const approveRequest = useCallback((
    requestId: string,
    adminId: string,
    adminName: string,
    adminRole: string,
    notes?: string,
  ) => {
    let approvedReq: SubscriptionRequest | undefined;

    setPendingRequests(prev => {
      const updated = prev.map(req => {
        if (req.id === requestId) {
          approvedReq = { ...req, status: 'approved' as const, approvedBy: adminName, approvalDate: new Date().toISOString(), notes };
          return approvedReq;
        }
        return req;
      });
      saveRequests(updated);
      return updated;
    });

    setApprovalHistory(prev => {
      const updated = [
        ...prev,
        {
          id: `action-${Date.now()}`,
          requestId,
          adminId,
          adminName,
          adminRole: adminRole as 'superadmin' | 'finance',
          action: 'approved' as const,
          timestamp: new Date().toISOString(),
          notes,
        },
      ];
      saveHistory(updated);
      return updated;
    });

    // Fire local notification (non-blocking)
    if (approvedReq) {
      sendSubscriptionApprovedNotification(approvedReq.subscriptionPlan, requestId).catch(() => {});
      // Also send backend notification so the customer sees it in their notification bell
      sendNotification({
        userId: approvedReq.userId,
        type: 'subscription',
        title: 'Subscription Approved',
        body: `Your ${approvedReq.subscriptionPlan} subscription has been approved! Your account is now active.`,
      }).catch(() => {});
    }
  }, [saveRequests, saveHistory]);

  const rejectRequest = useCallback((
    requestId: string,
    adminId: string,
    adminName: string,
    reason: string,
    notes?: string,
  ) => {
    let rejectedReq: SubscriptionRequest | undefined;

    setPendingRequests(prev => {
      const updated = prev.map(req => {
        if (req.id === requestId) {
          rejectedReq = { ...req, status: 'rejected' as const, rejectionReason: reason, approvalDate: new Date().toISOString(), notes };
          return rejectedReq;
        }
        return req;
      });
      saveRequests(updated);
      return updated;
    });

    setApprovalHistory(prev => {
      const updated = [
        ...prev,
        {
          id: `action-${Date.now()}`,
          requestId,
          adminId,
          adminName,
          adminRole: 'superadmin' as const,
          action: 'rejected' as const,
          reason,
          timestamp: new Date().toISOString(),
          notes,
        },
      ];
      saveHistory(updated);
      return updated;
    });

    // Fire local notification (non-blocking)
    if (rejectedReq) {
      sendSubscriptionRejectedNotification(rejectedReq.subscriptionPlan, reason, requestId).catch(() => {});
      // Also send backend notification so the customer sees it in their notification bell
      sendNotification({
        userId: rejectedReq.userId,
        type: 'subscription',
        title: 'Subscription Request Rejected',
        body: `Your ${rejectedReq.subscriptionPlan} subscription request was not approved. Reason: ${reason}`,
      }).catch(() => {});
    }
  }, [saveRequests, saveHistory]);

  const activateAccount = useCallback((
    requestId: string,
    adminId: string,
    adminName: string,
  ) => {
    let activatedReq: SubscriptionRequest | undefined;

    setPendingRequests(prev => {
      const updated = prev.map(req => {
        if (req.id === requestId) {
          activatedReq = { ...req, status: 'activated' as const, activationDate: new Date().toISOString() };
          return activatedReq;
        }
        return req;
      });
      saveRequests(updated);
      return updated;
    });

    setApprovalHistory(prev => {
      const updated = [
        ...prev,
        {
          id: `action-${Date.now()}`,
          requestId,
          adminId,
          adminName,
          adminRole: 'superadmin' as const,
          action: 'activated' as const,
          timestamp: new Date().toISOString(),
        },
      ];
      saveHistory(updated);
      return updated;
    });

    // Auto-activate subscription in auth-context (non-blocking)
    if (activatedReq && onActivateSubscription) {
      const req = activatedReq;
      // Subscription expires 1 year from activation
      const expiresAt = new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString();
      // Derive pickupsRemaining from planPrice heuristic; -1 = unlimited for premium plans
      const pickupsRemaining = req.planPrice >= 180 ? -1 : 4;

      onActivateSubscription(req.userId, {
        planId: req.planId || req.subscriptionPlan.toLowerCase().replace(/\s+/g, '_'),
        planName: req.subscriptionPlan,
        expiresAt,
        pickupsRemaining,
      }).catch(err => console.warn('[SubscriptionApproval] Failed to activate subscription:', err));
    }

    // Fire local notification (non-blocking)
    if (activatedReq) {
      sendSubscriptionActivatedNotification(activatedReq.subscriptionPlan, requestId).catch(() => {});
      // Also send backend notification so the customer sees it in their notification bell
      sendNotification({
        userId: activatedReq.userId,
        type: 'subscription',
        title: 'Subscription Activated',
        body: `Your ${activatedReq.subscriptionPlan} subscription is now active. You can start requesting pickups!`,
      }).catch(() => {});
    }
  }, [saveRequests, saveHistory, onActivateSubscription]);

  const getRequestById = useCallback((requestId: string) => {
    return pendingRequests.find(req => req.id === requestId);
  }, [pendingRequests]);

  const getRequestsByStatus = useCallback((status: SubscriptionRequest['status']) => {
    return pendingRequests
      .filter(req => req.status === status)
      .sort((a, b) => new Date(b.requestDate).getTime() - new Date(a.requestDate).getTime());
  }, [pendingRequests]);

  const getRequestsByUserId = useCallback((userId: string) => {
    return pendingRequests
      .filter(req => req.userId === userId)
      .sort((a, b) => new Date(b.requestDate).getTime() - new Date(a.requestDate).getTime());
  }, [pendingRequests]);

  const getApprovalHistory = useCallback((requestId?: string) => {
    return requestId
      ? approvalHistory.filter(action => action.requestId === requestId)
      : approvalHistory;
  }, [approvalHistory]);

  /**
   * Create a new subscription approval request.
   * Called automatically from payment-confirmation.tsx after a successful payment.
   * Returns the new request ID.
   */
  const addSubscriptionRequest = useCallback(async (
    request: Omit<SubscriptionRequest, 'id' | 'status' | 'requestDate'>,
  ): Promise<string> => {
    const newRequest: SubscriptionRequest = {
      ...request,
      id: `req-${Date.now()}-${Math.random().toString(36).substr(2, 6)}`,
      status: 'pending',
      requestDate: new Date().toISOString(),
    };

    setPendingRequests(prev => {
      const updated = [newRequest, ...prev];
      saveRequests(updated);
      return updated;
    });

    return newRequest.id;
  }, [saveRequests]);

  const getStats = useCallback(() => {
    return {
      pending: pendingRequests.filter(r => r.status === 'pending').length,
      approved: pendingRequests.filter(r => r.status === 'approved').length,
      activated: pendingRequests.filter(r => r.status === 'activated').length,
      rejected: pendingRequests.filter(r => r.status === 'rejected').length,
    };
  }, [pendingRequests]);

  return (
    <SubscriptionApprovalContext.Provider
      value={{
        pendingRequests,
        approvalHistory,
        isLoading,
        approveRequest,
        rejectRequest,
        activateAccount,
        getRequestById,
        getRequestsByStatus,
        getRequestsByUserId,
        getApprovalHistory,
        addSubscriptionRequest,
        getStats,
      }}
    >
      {children}
    </SubscriptionApprovalContext.Provider>
  );
}

export function useSubscriptionApproval() {
  const context = useContext(SubscriptionApprovalContext);
  if (!context) {
    throw new Error('useSubscriptionApproval must be used within SubscriptionApprovalProvider');
  }
  return context;
}
